-- AlterTable
ALTER TABLE `Config` MODIFY `status` VARCHAR(191) NOT NULL DEFAULT '1',
    MODIFY `isSystem` VARCHAR(191) NOT NULL DEFAULT '0';

-- AlterTable
ALTER TABLE `Dictionary` MODIFY `status` VARCHAR(191) NOT NULL DEFAULT '1',
    MODIFY `isSystem` VARCHAR(191) NOT NULL DEFAULT '0';

-- AlterTable
ALTER TABLE `DictionaryItem` MODIFY `status` VARCHAR(191) NOT NULL DEFAULT '1';

-- AlterTable
ALTER TABLE `Role` MODIFY `status` VARCHAR(191) NOT NULL DEFAULT '1',
    MODIFY `isSystem` VARCHAR(191) NOT NULL DEFAULT '0';

-- AlterTable
ALTER TABLE `User` MODIFY `status` VARCHAR(191) NOT NULL DEFAULT '1',
    MODIFY `isSystem` VARCHAR(191) NOT NULL DEFAULT '0';
